export DEBUG=true
export MYSQL_USERNAME=root
export MYSQL_PASSWORD=root
export MYSQL_DATABASE=noah
export MYSQL_HOST=0.0.0.0
export MYSQL_PORT=3306

export SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=''
export SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=''